### ISSUE TITLE
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

### ISSUE THREAD

**Issue by paulywill** [patrickleet/streaming-ssr-react-styled-components#18]
No doubt getting ahead of myself without reading all your articles fully, but when firing up your docker I'm receiving the following:

`dev_1  | Browserslist: caniuse-lite is outdated. Please run next command 'npm update'`

Screenshot:
![image](https://user-images.githubusercontent.com/602422/72960665-9697ef00-3d7c-11ea-941a-c4b0ebf55af3.png)

Obviously this is not working when I try `npm update` outside the docker running for this repo, so how do I resolve in the docker image?

Again, getting ahead of myself no doubt and apologize for not doing more research.

**Comment by patrickleet** [comment]
fixed

**Comment by paulywill** [comment]
Still getting the error message.

There's few other ppl reporting the same for that package: https://github.com/postcss/autoprefixer/issues/1184

**Comment by ccemeraldeyes** [comment]
FIXED HOW

**Comment by crycx** [comment]
Yes how ?

**Comment by razvanbh** [comment]
Deleting package-lock.json and performing npm install afterwards fixed it for me.

**Comment by koutsenko** [comment]
> Deleting package-lock.json and performing npm install afterwards fixed it for me.

Not helped for me

**Comment by paulywill** [comment]
@razvanbh same for me, I think we were just curious what the fix was. Maybe a simple dep update?

**Comment by patrickleet** [comment]
yes - by updating dependencies

**Comment by patrickleet** [comment]
the bots did it https://hackernoon.com/bring-in-the-bots-and-let-them-maintain-our-code-gh3s33n9
